// pulsar-gen-swift — self-contained host tool used by the SwiftPM build-tool plugin.
// Reads a .pulsar bundle and emits a typed Swift accessor. Foundation + Compression only
// (no UIKit), so it builds for the host (macOS) inside the plugin sandbox.
//
//   pulsar-gen-swift <input.pulsar> <output.swift>

import Foundation
import Compression

// MARK: - Minimal zip reader (STORE + DEFLATE)

enum Zip {
  static func read(_ data: Data) throws -> [String: Data] {
    let bytes = [UInt8](data)
    let count = bytes.count
    func u16(_ o: Int) -> Int { Int(bytes[o]) | (Int(bytes[o + 1]) << 8) }
    func u32(_ o: Int) -> Int {
      Int(bytes[o]) | (Int(bytes[o + 1]) << 8) | (Int(bytes[o + 2]) << 16) | (Int(bytes[o + 3]) << 24)
    }
    var eocd = -1
    var i = count - 22
    while i >= 0 { if u32(i) == 0x0605_4b50 { eocd = i; break }; i -= 1 }
    guard eocd >= 0 else { throw Err("not a zip") }
    let entryCount = u16(eocd + 10)
    var ptr = u32(eocd + 16)
    var out: [String: Data] = [:]
    for _ in 0..<entryCount {
      guard u32(ptr) == 0x0201_4b50 else { throw Err("bad central dir") }
      let method = u16(ptr + 10)
      let compSize = u32(ptr + 20)
      let uncompSize = u32(ptr + 24)
      let nameLen = u16(ptr + 28)
      let extraLen = u16(ptr + 30)
      let commentLen = u16(ptr + 32)
      let localOff = u32(ptr + 42)
      let name = String(decoding: bytes[(ptr + 46)..<(ptr + 46 + nameLen)], as: UTF8.self)
      let lNameLen = u16(localOff + 26)
      let lExtraLen = u16(localOff + 28)
      let dataStart = localOff + 30 + lNameLen + lExtraLen
      let raw = Data(bytes[dataStart..<(dataStart + compSize)])
      if !name.hasSuffix("/") {
        out[name] = method == 0 ? raw : try inflate(raw, size: uncompSize)
      }
      ptr += 46 + nameLen + extraLen + commentLen
    }
    return out
  }

  private static func inflate(_ data: Data, size: Int) throws -> Data {
    if size == 0 { return Data() }
    var dst = Data(count: size)
    let n = dst.withUnsafeMutableBytes { d in
      data.withUnsafeBytes { s in
        compression_decode_buffer(
          d.bindMemory(to: UInt8.self).baseAddress!, size,
          s.bindMemory(to: UInt8.self).baseAddress!, data.count, nil, COMPRESSION_ZLIB)
      }
    }
    guard n == size else { throw Err("inflate failed") }
    return dst
  }
}

struct Err: Error, CustomStringConvertible { let m: String; init(_ m: String) { self.m = m }; var description: String { m } }

// MARK: - Manifest

struct Manifest: Codable {
  let schema: String
  let id: String
  let name: String
  let hash: String?
  let presets: [Preset]
  struct Preset: Codable { let id: String; let name: String }
}

// MARK: - Emit (matches @swmansion/pulsar-gen swift target)

func pascalCase(_ s: String) -> String {
  let parts = s.split { !$0.isLetter && !$0.isNumber }
  let p = parts.map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
  return (p.first?.isLetter == true || p.first == "_") ? p : "Bundle" + p
}

func emitSwift(_ manifest: Manifest, assetName: String) -> String {
  let type = pascalCase(manifest.name)
  let ids = manifest.presets.map { $0.id }
  let fields = ids.map { "        public let \($0): PresetHandle" }.joined(separator: "\n")
  let args = ids.map { "\($0): r[\"\($0)\"]" }.joined(separator: ", ")
  let idList = ids.map { "\"\($0)\"" }.joined(separator: ", ")
  return """
  // Code generated by pulsar-gen. DO NOT EDIT.
  // Bundle: \(manifest.id) (\(ids.count) preset\(ids.count == 1 ? "" : "s"))
  import Pulsar

  public enum \(type) {
      public static let assetName = "\(assetName)"
      public static let bundleId = "\(manifest.id)"
      public static let contentHash = "\(manifest.hash ?? "")"

      public struct Presets {
  \(fields)
      }

      public static let descriptor = BundleDescriptor<Presets>(
          assetName: assetName,
          bundleId: bundleId,
          contentHash: contentHash,
          presetIds: [\(idList)],
          build: { r in Presets(\(args)) }
      )
  }

  """
}

// MARK: - Entry

let args = CommandLine.arguments
guard args.count == 3 else {
  FileHandle.standardError.write(Data("usage: pulsar-gen-swift <input.pulsar> <output.swift>\n".utf8))
  exit(2)
}
do {
  let input = URL(fileURLWithPath: args[1])
  let output = URL(fileURLWithPath: args[2])
  let files = try Zip.read(try Data(contentsOf: input))
  guard let manifestData = files["manifest.json"] else { throw Err("missing manifest.json") }
  let manifest = try JSONDecoder().decode(Manifest.self, from: manifestData)
  let assetName = input.deletingPathExtension().lastPathComponent
  try emitSwift(manifest, assetName: assetName).write(to: output, atomically: true, encoding: .utf8)
} catch {
  FileHandle.standardError.write(Data("pulsar-gen-swift: \(error)\n".utf8))
  exit(1)
}
