// Code generated by pulsar-gen. DO NOT EDIT.
// Bundle: com.swmansion.pulsar.examples (4 presets)
import 'package:pulsar_haptics/pulsar_haptics.dart';

/// The loaded bundle. Presets are direct members — bundle.agentpattern.play() — and the
/// bundle's own members sit alongside them; pulsar-gen rejects a preset named after one.
class HapticsBundlePresets {
  HapticsBundlePresets(BundleResolver r)
      : _r = r,
        agentpattern = r['agentpattern'],
        fanfare = r['fanfare'],
        arcadeBonusAlert = r['arcadeBonusAlert'],
        lottie = r['lottie'];

  final BundleResolver _r;
  final PresetHandle agentpattern;
  final PresetHandle fanfare;
  final PresetHandle arcadeBonusAlert;
  final PresetHandle lottie;

  String get id => _r.bundleId;
  String get contentHash => _r.contentHash;

  /// Look a preset up by an id only known at runtime.
  PresetHandle? get(String id) => _r.handle(id);

  /// Release the native patterns this bundle parsed.
  void dispose() => _r.dispose();
}

final hapticsBundle = BundleDescriptor<HapticsBundlePresets>(
  assetName: 'assets/pulsar/hapticsBundle.pulsar',
  bundleId: 'com.swmansion.pulsar.examples',
  contentHash: 'sha256-59d4fbc5487eeb028df1c073ec782d00043b88b0aef12fb9f4ad3d57e51cca82',
  presetIds: const ['agentpattern', 'fanfare', 'arcadeBonusAlert', 'lottie'],
  build: HapticsBundlePresets.new,
);
