# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
use_local_pulsar_ios = ENV['USE_LOCAL_PULSAR_IOS'] == '1'

if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'example' do
  config = use_native_modules!

  if use_local_pulsar_ios
    Pod::UI.puts 'Using local Pulsar-haptics pod from iOS/Pulsar'.green
    pod 'Pulsar-haptics', :path => '../../../iOS/Pulsar'
  else
    Pod::UI.puts 'Using published Pulsar-haptics pod from CocoaPods'.green
  end

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    hermes_cli_path = File.realpath(
      File.join(__dir__, '..', 'node_modules', 'hermes-compiler', 'hermesc', 'osx-bin', 'hermesc')
    )

    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.xcconfigs.each do |config_name, config_file|
        config_file.attributes['HERMES_CLI_PATH'] = hermes_cli_path
        config_file.save_as(aggregate_target.xcconfig_path(config_name))
      end
    end
  end
end
