// Code generated by pulsar-gen. DO NOT EDIT.
// Bundle: com.swmansion.pulsar.examples (4 presets)
package com.swmansion.pulsar.kmp.app.bundles

import com.swmansion.pulsar.kmp.bundle.BundleDescriptor
import com.swmansion.pulsar.kmp.bundle.BundleResolver
import com.swmansion.pulsar.kmp.bundle.PresetHandle

object HapticsBundle {
    const val assetName = "hapticsBundle.pulsar"
    const val bundleId = "com.swmansion.pulsar.examples"
    const val contentHash = "sha256-59d4fbc5487eeb028df1c073ec782d00043b88b0aef12fb9f4ad3d57e51cca82"

    /**
     * The loaded bundle. Presets are direct members — bundle.agentpattern.play() — and the
     * bundle's own members sit alongside them; pulsar-gen rejects a preset named after one.
     */
    class Presets(private val r: BundleResolver) {
        val agentpattern: PresetHandle = r["agentpattern"]
        val fanfare: PresetHandle = r["fanfare"]
        val arcadeBonusAlert: PresetHandle = r["arcadeBonusAlert"]
        val lottie: PresetHandle = r["lottie"]

        val id: String get() = r.bundleId
        val revision: Int get() = r.revision
        val contentHash: String get() = r.contentHash

        /** Look a preset up by an id only known at runtime. */
        fun get(id: String): PresetHandle? = r.handle(id)

        /** Release the native patterns this bundle parsed. */
        fun dispose() = r.dispose()
    }

    val descriptor = BundleDescriptor(
        assetName = assetName,
        bundleId = bundleId,
        contentHash = contentHash,
        presetIds = listOf("agentpattern", "fanfare", "arcadeBonusAlert", "lottie"),
        build = ::Presets,
    )
}
