#!/usr/bin/env node
// Generates a typed `<name>.bundle.ts` module next to every `.pulsar` in a directory.
//
//   node scripts/pulsar-gen-rn.mjs <dir> [<dir> ...]     (default: ./assets)
//
// Self-contained (node:zlib only) so it needs no extra dependency in the app.
// Mirrors tools/pulsar-gen/src/emit/rn.ts — keep the two in sync.

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';
import { inflateRawSync } from 'node:zlib';

const SIDECAR_SCHEMA = 'pulsar.sidecar/1';

function readEntries(bundlePath) {
  const buf = readFileSync(bundlePath);
  // Locate End Of Central Directory.
  let eocd = -1;
  for (let i = buf.length - 22; i >= 0; i--) {
    if (buf.readUInt32LE(i) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error(`${bundlePath}: not a zip`);
  let ptr = buf.readUInt32LE(eocd + 16);
  const count = buf.readUInt16LE(eocd + 10);
  const entries = {};
  for (let n = 0; n < count; n++) {
    const method = buf.readUInt16LE(ptr + 10);
    const compSize = buf.readUInt32LE(ptr + 20);
    const nameLen = buf.readUInt16LE(ptr + 28);
    const extraLen = buf.readUInt16LE(ptr + 30);
    const commentLen = buf.readUInt16LE(ptr + 32);
    const localOff = buf.readUInt32LE(ptr + 42);
    const name = buf.toString('utf8', ptr + 46, ptr + 46 + nameLen);
    const lNameLen = buf.readUInt16LE(localOff + 26);
    const lExtraLen = buf.readUInt16LE(localOff + 28);
    const start = localOff + 30 + lNameLen + lExtraLen;
    const raw = buf.subarray(start, start + compSize);
    entries[name] = method === 0 ? raw : inflateRawSync(raw);
    ptr += 46 + nameLen + extraLen + commentLen;
  }
  return entries;
}

function readJson(entries, path, where) {
  const bytes = entries[path];
  if (!bytes) throw new Error(`${where}: missing "${path}"`);
  try {
    return JSON.parse(bytes.toString('utf8'));
  } catch (e) {
    throw new Error(`${where}: "${path}" is invalid JSON — ${e.message}`);
  }
}

function buildSidecar(entries, where) {
  const manifest = readJson(entries, 'manifest.json', where);
  const presets = {};
  const droppedAnimation = [];
  for (const p of manifest.presets) {
    const pattern = readJson(entries, p.haptics, where);
    if (!Array.isArray(pattern.discretePattern) || !pattern.continuousPattern) {
      throw new Error(`${where}: "${p.haptics}" is not a device pattern`);
    }
    presets[p.id] = {
      name: p.name,
      pattern,
      audio: !!p.audio,
      animation: !!p.animation,
    };
    if (p.duration !== undefined) presets[p.id].duration = p.duration;

    // Only a JSON Lottie can be inlined; a dotLottie (.lottie) is a binary zip.
    if (p.animation) {
      if (/\.json$/i.test(p.animation.src)) {
        const lottie = { source: readJson(entries, p.animation.src, where) };
        if (p.animation.frameRate !== undefined)
          lottie.frameRate = p.animation.frameRate;
        if (p.animation.totalFrames !== undefined)
          lottie.totalFrames = p.animation.totalFrames;
        presets[p.id].lottie = lottie;
      } else {
        droppedAnimation.push(p.id);
      }
    }
  }
  const sidecar = {
    schema: SIDECAR_SCHEMA,
    id: manifest.id,
    contentHash: manifest.hash ?? '',
    presets,
  };
  if (manifest.revision !== undefined) sidecar.revision = manifest.revision;

  return { sidecar, droppedAnimation };
}

const dirs = process.argv.slice(2);
if (dirs.length === 0) dirs.push('assets');

for (const dir of dirs) {
  for (const file of readdirSync(dir)) {
    if (!file.endsWith('.pulsar')) continue;
    const name = basename(file, '.pulsar');
    const bundlePath = join(dir, file);
    const { sidecar, droppedAnimation } = buildSidecar(
      readEntries(bundlePath),
      bundlePath
    );

    // Keep the payload minified: it ships inside the app's JS bundle.
    const serialized = JSON.stringify(sidecar);
    const definition =
      serialized.slice(0, -1) +
      `,"asset":require(${JSON.stringify(`./${name}.pulsar`)})}`;
    const out = join(dir, `${name}.bundle.ts`);
    writeFileSync(
      out,
      '// Code generated by pulsar-gen. DO NOT EDIT.\n' +
        '// prettier-ignore\n' +
        "import { defineBundle } from 'react-native-pulsar';\n\n" +
        '// prettier-ignore\n' +
        `export const loadBundle = defineBundle(${definition});\n` +
        '// prettier-ignore\n' +
        "export type { PresetHandle } from 'react-native-pulsar';\n"
    );
    process.stderr.write(`pulsar-gen-rn: wrote ${out}\n`);

    if (droppedAnimation.length > 0) {
      process.stderr.write(
        `pulsar-gen-rn: warning: presets ${droppedAnimation.join(', ')} have an animation that ` +
          'could not be inlined (dotLottie `.lottie` is binary — re-export it as .json, or use ' +
          'the .pulsar binary).\n'
      );
    }
    for (const staleName of [`${name}.bundle.json`, `${name}.presets.json`]) {
      const stale = join(dir, staleName);
      if (!existsSync(stale)) continue;
      process.stderr.write(
        `pulsar-gen-rn: warning: ${stale} is from an old generated format and is no longer read; ` +
          'delete it and import the .bundle.ts module instead.\n'
      );
    }
  }
}
