// Code generated by pulsar-gen. DO NOT EDIT.
// prettier-ignore
import { defineBundle } from 'react-native-pulsar';

// prettier-ignore
export const loadBundle = defineBundle({"schema":"pulsar.sidecar/1","id":"com.acme.haptics","contentHash":"sha256-43ac6da47d3711e9cec972e35f3e520b40589a2db7e10d783d3adf3a6522d98e","presets":{"heartbeatV2":{"name":"Heartbeat V2","pattern":{"continuousPattern":{"amplitude":[{"time":0,"value":0},{"time":10,"value":0.8},{"time":120,"value":0}],"frequency":[{"time":0,"value":0.2},{"time":1000,"value":0.2}]},"discretePattern":[{"time":0,"amplitude":0.9,"frequency":0.2},{"time":120,"amplitude":0.6,"frequency":0.2}]},"audio":true,"animation":true,"duration":1200,"lottie":{"source":{"v":"5.7.4","fr":60,"ip":0,"op":72,"w":100,"h":100,"layers":[]},"frameRate":60,"totalFrames":72}},"explosion":{"name":"Explosion","pattern":{"continuousPattern":{"amplitude":[{"time":0,"value":1},{"time":200,"value":0}],"frequency":[{"time":0,"value":0.8}]},"discretePattern":[{"time":0,"amplitude":1,"frequency":0.9}]},"audio":true,"animation":true,"duration":800}},"revision":7,"asset":require("./acme-pack.pulsar")});
// prettier-ignore
export type { PresetHandle } from 'react-native-pulsar';
