// Code generated by pulsar-gen. DO NOT EDIT.
// Bundle: com.acme.haptics (2 presets)
import 'package:pulsar_haptics/pulsar_haptics.dart';

class AcmePackPresets {
  AcmePackPresets(BundleResolver r)
      : heartbeatV2 = r['heartbeatV2'],
        explosion = r['explosion'];

  final PresetHandle heartbeatV2;
  final PresetHandle explosion;
}

final acmePack = BundleDescriptor<AcmePackPresets>(
  assetName: 'assets/pulsar/acme-pack.pulsar',
  bundleId: 'com.acme.haptics',
  contentHash: 'sha256-355197402b5ff6460e2dbefcf9048bd6868234f102c3f8c13fbb932f653a9790',
  presetIds: const ['heartbeatV2', 'explosion'],
  build: AcmePackPresets.new,
);
