// Code generated by pulsar-gen. DO NOT EDIT.
// Bundle: com.acme.haptics (2 presets)
package com.swmansion.pulsar.bundles

import com.swmansion.pulsar.bundle.BundleDescriptor
import com.swmansion.pulsar.bundle.BundleResolver
import com.swmansion.pulsar.bundle.PresetHandle

object AcmePack {
    const val assetName = "acme-pack.pulsar"
    const val bundleId = "com.acme.haptics"
    const val contentHash = "sha256-43ac6da47d3711e9cec972e35f3e520b40589a2db7e10d783d3adf3a6522d98e"

    class Presets(r: BundleResolver) {
        val heartbeatV2: PresetHandle = r["heartbeatV2"]
        val explosion: PresetHandle = r["explosion"]
    }

    val descriptor = BundleDescriptor(
        assetName = assetName,
        bundleId = bundleId,
        contentHash = contentHash,
        presetIds = listOf("heartbeatV2", "explosion"),
        build = ::Presets,
    )
}
