// Code generated by pulsar-gen. DO NOT EDIT.
// Bundle: com.acme.haptics (2 presets)
import Pulsar

public enum AcmePack {
    public static let assetName = "acme-pack"
    public static let bundleId = "com.acme.haptics"
    public static let contentHash = "sha256-43ac6da47d3711e9cec972e35f3e520b40589a2db7e10d783d3adf3a6522d98e"

    public struct Presets {
        public let heartbeatV2: PresetHandle
        public let explosion: PresetHandle
    }

    public static let descriptor = BundleDescriptor<Presets>(
        assetName: assetName,
        bundleId: bundleId,
        contentHash: contentHash,
        presetIds: ["heartbeatV2", "explosion"],
        build: { r in Presets(heartbeatV2: r["heartbeatV2"], explosion: r["explosion"]) }
    )
}
