// Code generated by pulsar-gen. DO NOT EDIT.
// Bundle: com.acme.haptics (2 presets)
import Pulsar

public enum AcmePack {
    public static let assetName = "acme-pack"
    public static let bundleId = "com.acme.haptics"
    public static let contentHash = "sha256-355197402b5ff6460e2dbefcf9048bd6868234f102c3f8c13fbb932f653a9790"

    public struct Presets {
        public let heartbeatV2: PresetHandle
        public let explosion: PresetHandle
    }

    public static let descriptor = BundleDescriptor<Presets>(
        assetName: assetName,
        bundleId: bundleId,
        contentHash: contentHash,
        presetIds: ["heartbeatV2", "explosion"],
        build: { r in Presets(heartbeatV2: r["heartbeatV2"], explosion: r["explosion"]) }
    )
}
