// Code generated by pulsar-gen. DO NOT EDIT.
// Bundle: com.acme.haptics (2 presets)
import 'package:pulsar_haptics/pulsar_haptics.dart';

class AcmePackPresets {
  AcmePackPresets(BundleResolver r)
      : heartbeatV2 = r['heartbeatV2'],
        explosion = r['explosion'];

  final PresetHandle heartbeatV2;
  final PresetHandle explosion;
}

final acmePack = BundleDescriptor<AcmePackPresets>(
  assetName: 'assets/pulsar/acme-pack.pulsar',
  bundleId: 'com.acme.haptics',
  contentHash: 'sha256-43ac6da47d3711e9cec972e35f3e520b40589a2db7e10d783d3adf3a6522d98e',
  presetIds: const ['heartbeatV2', 'explosion'],
  build: AcmePackPresets.new,
);
