name: Bug report
description: Report an issue with Pulsar here.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before you proceed make sure to check whether there are similar issues in the repository

  - type: markdown
    attributes:
      value: |
        ## Required information

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear, concise and descriptive explanation of what the bug is. Include screenshots or a video if needed. Tell us what were you expecting to happen instead of what is happening now.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: repro
    attributes:
      label: Link to a repository
      description: |
        Please provide a link to a repository on GitHub under your username that reproduces the issue.   
        Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve.
        Issues without a reproduction are likely to go stale.
      placeholder: https://github.com/username/repo
    validations:
      required: true

  - type: dropdown
    id: sdk
    attributes:
      label: SDK
      description: Which Pulsar SDK are you using?
      options:
        - React Native
        - iOS
        - Android
    validations:
      required: true

  - type: input
    id: pulsar-version
    attributes:
      label: Pulsar version
      description: What version of Pulsar are you using?
      placeholder: 1.0.0
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Platform
      description: On what platform is your application running?
      multiple: true
      options:
        - Android
        - iOS
    validations:
      required: true

  - type: input
    id: react-native-version
    attributes:
      label: React Native version
      description: (React Native SDK only) What version of React Native are you using? 
      placeholder: 0.81.5

  - type: dropdown
    id: build-type
    attributes:
      label: Build type
      description: What is the build configuration of your app?
      multiple: true
      options:
        - Debug
        - Release
    validations:
      required: true

  - type: input
    id: device-model
    attributes:
      label: Device model
      description: What device are you experiencing this problem on? Specify the full device name along with the OS version it's running.
      placeholder: iPhone 17 Pro, iOS 26.2
    validations:
      required: true

  - type: dropdown
    id: host-machine
    attributes:
      label: Host machine
      description: What is the operating system of the machine you are developing on?
      options:
        - macOS
        - Windows
        - Linux

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Providing as much information as possible greatly helps us with reproducing the issues.


