// Code generated by pulsar-gen. DO NOT EDIT.
// Bundle: com.swmansion.pulsar.examples (4 presets)
import Pulsar

public enum HapticsBundle {
    public static let assetName = "hapticsBundle"
    public static let bundleId = "com.swmansion.pulsar.examples"
    public static let contentHash = "sha256-59d4fbc5487eeb028df1c073ec782d00043b88b0aef12fb9f4ad3d57e51cca82"

    public struct Presets {
        public let agentpattern: PresetHandle
        public let fanfare: PresetHandle
        public let arcadeBonusAlert: PresetHandle
        public let lottie: PresetHandle
    }

    public static let descriptor = BundleDescriptor<Presets>(
        assetName: assetName,
        bundleId: bundleId,
        contentHash: contentHash,
        presetIds: ["agentpattern", "fanfare", "arcadeBonusAlert", "lottie"],
        build: { r in Presets(agentpattern: r["agentpattern"], fanfare: r["fanfare"], arcadeBonusAlert: r["arcadeBonusAlert"], lottie: r["lottie"]) }
    )
}
