package com.swmansion.pulsar.gradle

import groovy.json.JsonSlurper
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.ByteArrayInputStream
import java.io.File
import java.util.zip.ZipInputStream

/**
 * Reads every `*.pulsar` bundle in [bundlesDir], emits a typed Kotlin accessor per bundle into
 * [generatedSrcDir], and copies the bundle into `[generatedAssetsDir]/pulsar/` so it ships in the
 * APK's assets. Runs before Kotlin compilation, so dropping in an updated bundle refreshes the types.
 */
abstract class GeneratePulsarBundlesTask : DefaultTask() {
    @get:InputDirectory @get:Optional
    abstract val bundlesDir: DirectoryProperty

    @get:OutputDirectory
    abstract val generatedSrcDir: DirectoryProperty

    @get:OutputDirectory
    abstract val generatedAssetsDir: DirectoryProperty

    @get:Input
    abstract val packageName: Property<String>

    @TaskAction
    fun generate() {
        val dir = bundlesDir.orNull?.asFile
        val srcOut = generatedSrcDir.get().asFile.also { it.mkdirs() }
        val assetsOut = generatedAssetsDir.get().asFile.resolve("pulsar").also { it.mkdirs() }
        if (dir == null || !dir.exists()) return

        dir.listFiles { f -> f.isFile && f.extension == "pulsar" }?.sortedBy { it.name }?.forEach { file ->
            val entries = unzip(file.readBytes())
            val manifestBytes = entries["manifest.json"]
                ?: error("Pulsar: ${file.name} is missing manifest.json")

            @Suppress("UNCHECKED_CAST")
            val manifest = JsonSlurper().parseText(String(manifestBytes)) as Map<String, Any?>
            val name = manifest["name"] as? String ?: error("Pulsar: ${file.name} manifest missing 'name'")
            val typeName = pascalCase(name)

            val code = emitKotlin(manifest, assetName = "pulsar/${file.name}", packageName = packageName.get())
            File(srcOut, "$typeName.kt").writeText(code)
            file.copyTo(File(assetsOut, file.name), overwrite = true)
            logger.lifecycle("pulsar-gen: ${file.name} -> $typeName.kt")
        }
    }

    private fun unzip(bytes: ByteArray): Map<String, ByteArray> {
        val out = LinkedHashMap<String, ByteArray>()
        ZipInputStream(ByteArrayInputStream(bytes)).use { zis ->
            var entry = zis.nextEntry
            while (entry != null) {
                if (!entry.isDirectory) out[entry.name] = zis.readBytes()
                zis.closeEntry()
                entry = zis.nextEntry
            }
        }
        return out
    }
}

internal fun pascalCase(input: String): String {
    val parts = input.split(Regex("[^A-Za-z0-9]+")).filter { it.isNotEmpty() }
    val p = parts.joinToString("") { it.replaceFirstChar { c -> c.uppercaseChar() } }
    return if (p.firstOrNull()?.isLetter() == true || p.firstOrNull() == '_') p else "Bundle$p"
}

@Suppress("UNCHECKED_CAST")
internal fun emitKotlin(manifest: Map<String, Any?>, assetName: String, packageName: String): String {
    val bundleId = manifest["id"] as? String ?: ""
    val hash = manifest["hash"] as? String ?: ""
    val typeName = pascalCase(manifest["name"] as String)
    val presets = (manifest["presets"] as? List<Map<String, Any?>>).orEmpty()
    val ids = presets.map { it["id"] as String }

    val fields = ids.joinToString("\n") { "        val $it: PresetHandle = r[\"$it\"]" }
    val idList = ids.joinToString(", ") { "\"$it\"" }

    return buildString {
        appendLine("// Code generated by pulsar-gen. DO NOT EDIT.")
        appendLine("// Bundle: $bundleId (${ids.size} preset${if (ids.size == 1) "" else "s"})")
        appendLine("package $packageName")
        appendLine()
        appendLine("import com.swmansion.pulsar.bundle.BundleDescriptor")
        appendLine("import com.swmansion.pulsar.bundle.BundleResolver")
        appendLine("import com.swmansion.pulsar.bundle.PresetHandle")
        appendLine()
        appendLine("object $typeName {")
        appendLine("    const val assetName = \"$assetName\"")
        appendLine("    const val bundleId = \"$bundleId\"")
        appendLine("    const val contentHash = \"$hash\"")
        appendLine()
        appendLine("    class Presets(r: BundleResolver) {")
        appendLine(fields)
        appendLine("    }")
        appendLine()
        appendLine("    val descriptor = BundleDescriptor(")
        appendLine("        assetName = assetName,")
        appendLine("        bundleId = bundleId,")
        appendLine("        contentHash = contentHash,")
        appendLine("        presetIds = listOf($idList),")
        appendLine("        build = ::Presets,")
        appendLine("    )")
        appendLine("}")
    }
}
