import type { HapticPattern } from 'pulsar-haptics';

export type WebPresetData = {
  name: string;
  description: string;
  tags: string[];
  duration: number;
  pattern: HapticPattern;
};

export type WebPresetEntry = {
  data: WebPresetData;
  image: string;
};

/**
 * Presets are read straight out of the docs' shared asset tree (the same files
 * the web presets playground uses), which is regenerated by
 * `web/Pulsar/scripts/generate-presets.ts`. Globbing rather than hand-listing
 * means a newly generated preset shows up here without touching this file.
 */
const patternModules = import.meta.glob<WebPresetData>(
  '../../../src/content/docs/assets/webPresets/*.json',
  { eager: true, import: 'default' },
);

const imageModules = import.meta.glob<string>('../../../src/content/docs/assets/webPresets/*.png', {
  eager: true,
  query: '?url',
  import: 'default',
});

function basename(path: string): string {
  return path.slice(path.lastIndexOf('/') + 1).replace(/\.\w+$/, '');
}

const imagesByName = new Map(
  Object.entries(imageModules).map(([path, url]) => [basename(path), url]),
);

export const PRESETS: WebPresetEntry[] = Object.entries(patternModules)
  .map(([path, data]) => ({ data, image: imagesByName.get(basename(path)) ?? '' }))
  .sort((left, right) => left.data.name.localeCompare(right.data.name));

/** Every tag present on at least one preset, in the order the tag groups define. */
export function collectTags(entries: WebPresetEntry[]): string[] {
  const seen = new Set<string>();
  entries.forEach((entry) => entry.data.tags.forEach((tag) => seen.add(tag)));
  return Array.from(seen);
}
