// Shared emitter helpers (portable — no Node APIs).

import type { BundleManifest, GenerateOptions } from '../types.ts';

export const DO_NOT_EDIT = 'Code generated by pulsar-gen. DO NOT EDIT.';

/** Asset base name (no extension), from options or the manifest id's last segment. */
export function resolveAssetName(manifest: BundleManifest, opts: GenerateOptions): string {
  if (opts.assetName) return opts.assetName;
  const seg = manifest.id.split('.').pop() || manifest.id;
  return seg.replace(/[^A-Za-z0-9._-]/g, '-');
}

export function contentHash(manifest: BundleManifest): string {
  return manifest.hash ?? '';
}
